### ISSUE TITLE
什么时候开始启用版本

### ISSUE THREAD

**Issue by MeowCold** [willnewii/qiniuClient#1]
什么时候开始启用版本和提供二进制文件 开心

**Comment by willnewii** [comment]
好啦,已经更新一些小功能.也上传了app文件,可以下载试试看🤓

**Comment by MeowCold** [comment]
感谢回复 😹可惜我是win10 x64

**Comment by willnewii** [comment]
哦哦~ 这样的话  明天我试试build一个win版本的.  但是,我觉得现在这个软件最好用的就是托盘上传,win是不支持的. 剩下的就只是普通的文件管理了.

**Comment by MeowCold** [comment]
原来你说的托盘是mac上的233 我理解有误，不过说实在的你这个界面比七牛官方的更直观些。我也说不上来为什么但确实觉得更喜欢你这个界面展示（除了留空有点大）

**Comment by willnewii** [comment]
新版更新了,以后都会有相应win的打包 [releases](https://github.com/willnewii/qiniuClient/releases)

**Comment by MeowCold** [comment]
由衷感谢
