### ISSUE TITLE
能否打包一个Linux的包啊

### ISSUE THREAD

**Issue by thtomatic** [willnewii/qiniuClient#101]
能否打包一个Linux的包啊

**Comment by abcfy2** [comment]
在 #102 解决了Linux编译问题。

临时在我的Release放上了Linux的软件包，可以测试一下: https://github.com/abcfy2/qiniuClient/releases/tag/tmp-release

**Comment by thtomatic** [comment]
> 在 #102 解决了Linux编译问题。
> 
> 临时在我的Release放上了Linux的软件包，可以测试一下: https://github.com/abcfy2/qiniuClient/releases/tag/tmp-release

感谢
