### ISSUE TITLE
开源的对象存储minio能支持一下么！

### ISSUE THREAD

**Issue by leonyff** [willnewii/qiniuClient#103]
我是使用自己部署的开源对象存储，兼容AWS的，[minio](https://github.com/minio/minio), 是否可以做一下支持！

**Comment by willnewii** [comment]
没接触过，我先了解一下哈~

**Comment by willnewii** [comment]
不好意思,拖了这么久.更新了.不过就是简单的实现了存取,不知道是不是对你有帮助.测试版链接.
[云存储管理客户端-0.4.2-beta-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.2-beta-win.exe)

**Comment by leonyff** [comment]
感谢啊，我安装使用是，返回的 markdown url链接很长！这个还能优化么？
![image](https://user-images.githubusercontent.com/38803732/68386631-6b4b2e00-0197-11ea-980e-8cd3f9e840eb.png)

**Comment by willnewii** [comment]
我才大概也许  应该可以能优化...  
一般来说当存储桶的私密存储的时候,上面会带有参数.(权限,过期时间什么的)
不确定这个是因为我直接用了aws的,还是别的原因.
我先确认一下是啥问题哈~

**Comment by willnewii** [comment]
更新了. 你可以再试试~   [云存储管理客户端-0.4.2-win-beta2.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.2-win-beta2.exe)

不过这里有个需要用户手动设置的地方. 为存储桶添加  可读的 policy . 然后应该就没问题了.
