### ISSUE TITLE
文件上传卡在 100%

### ISSUE THREAD

**Issue by no-today** [willnewii/qiniuClient#104]
![image](https://user-images.githubusercontent.com/34943822/67998111-1b013700-fc92-11e9-9f41-053942f7a350.png)

平台: 七牛云
文件类型: .mov
文件大小: 212MB

**Comment by inotoday** [comment]
批量上传、拖拉上传均有几率出现该问题，卡了很久我再拖拉一次又好了。

**Comment by willnewii** [comment]
收到~  稍后我也找个类似文件测试一下~  多谢

**Comment by houtnze** [comment]
很大概率会出现，我的做法是上传一次之后重启软件来避免上传第二个文件出问题

**Comment by willnewii** [comment]
更新了一下七牛SDK.  如果还有需要可以试试新版的,看看是否还有卡的情况.
