### ISSUE TITLE
文件上传腾讯云以后,文件地址一直在变

### ISSUE THREAD

**Issue by lmx920014697** [willnewii/qiniuClient#106]
文件上传腾讯云以后,文件地址一直在变,请问一下是什么情况

**Comment by willnewii** [comment]
您需要先去确认一下存储桶的[访问权限](https://cloud.tencent.com/document/product/436/13312#.E6.9D.83.E9.99.90.E7.B1.BB.E5.88.AB).

如果是`私有读写`，生成的url会有一些动态的参数，所以看起来就像是一直在变.
如果是`公有读私有写`或`公有读写`，就不会有问题,直接返回的就是一个文件路径.

![云存储管理客户端](https://user-images.githubusercontent.com/652003/68570706-3d6a3000-049c-11ea-913e-994ebadd8cde.jpg)

带锁的,就是私有读了.

**Comment by lmx920014697** [comment]
非常感谢

**Comment by lmx920014697** [comment]
> 您需要先去确认一下存储桶的[访问权限](https://cloud.tencent.com/document/product/436/13312#.E6.9D.83.E9.99.90.E7.B1.BB.E5.88.AB)。
> 
> 如果是`私有读写`，生成的网址会有一些动态的参数，那么看起来就像是一直在变。
> 如果是`公有读私有写`或`公有读写`，就不会有问题，直接返回的就是一个文件路径。
> 
> ![云存储管理客户端](https://user-images.githubusercontent.com/652003/68570706-3d6a3000-049c-11ea-913e-994ebadd8cde.jpg)
> 
> 带锁的，就是私有读了。



> 您需要先去确认一下存储桶的[访问权限](https://cloud.tencent.com/document/product/436/13312#.E6.9D.83.E9.99.90.E7.B1.BB.E5.88.AB)。
> 
> 如果是`私有读写`，生成的网址会有一些动态的参数，那么看起来就像是一直在变。
> 如果是`公有读私有写`或`公有读写`，就不会有问题，直接返回的就是一个文件路径。
> 
> ![云存储管理客户端](https://user-images.githubusercontent.com/652003/68570706-3d6a3000-049c-11ea-913e-994ebadd8cde.jpg)
> 
> 带锁的，就是私有读了。
非常感谢
