### ISSUE TITLE
关于七牛云上传时域名的选择

### ISSUE THREAD

**Issue by hebehan** [willnewii/qiniuClient#108]
![image](https://user-images.githubusercontent.com/8486219/69621883-de4f1280-107a-11ea-8e4e-d9df4ad39f17.png)

七牛上传时默认复制用的是临时域名，能默认选择固定的公司域名，然后复制的也是公司域名的地址嘛

**Comment by solarhell** [comment]
七牛后台上传的地方自己设置啊，和这个客户端没关系。

**Comment by hebehan** [comment]
我知道，我意思是能不能默认复制主要域名的，比如在哪能设置一下，一个bucket默认就是我想要的那个，而不是临时域名

**Comment by willnewii** [comment]
是说有一个默认保存用户自己选择的域名的功能.  对吧?

**Comment by hebehan** [comment]
是的，差不多这个意思，比如每个bucket默认选中上次选的域名，而不是重置到第一个

**Comment by willnewii** [comment]
了解~  这周手上有事.可能要迟一些~  下周补上

**Comment by willnewii** [comment]
抱歉拖了这么久.  更新了已经   有时间可以试试
- [云存储管理客户端-0.4.2-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.2-mac.dmg)
- [云存储管理客户端-0.4.2-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.2-win.exe)

**Comment by hebehan** [comment]
好的,非常感谢
