### ISSUE TITLE
求助，阿里云OSS登录后一直处于数据加载中

### ISSUE THREAD

**Issue by loyolove** [willnewii/qiniuClient#109]
<a href="https://sm.ms/image/nA2rfBzXlOSkUH6" target="_blank"><img src="https://i.loli.net/2019/12/01/nA2rfBzXlOSkUH6.png" ></a>
情况如图，测试了2个阿里云OSS账号都是这样的情况。

登录腾讯云储存是正常的。

有人遇到相同情况吗
求助，如何解决，谢谢大佬们。

**Comment by willnewii** [comment]
额...  应该是我的问题.   你阿里云的账号应该是一个文件都没有吧？

**Comment by loyolove** [comment]
> 额...应该是我的问题。你阿里云的账号应该是一个文件都没有吧？

是的，这个账号里是一个文件都没有；然后我又试了另一个存了很多内容的账号，也是一样的情况。一直处于数据加载中。

**Comment by loyolove** [comment]
> 额...应该是我的问题。你阿里云的账号应该是一个文件都没有吧？随便加个文件再试试？😅 不好意思。

刚刚我随便上传了个文件上去，真的好了，太神奇了吧。谢谢大佬，提供这么好用的工具。
（不过不知道为什么之前我测试了另一个存了内容的也会是这个情况，或许是缓存没清理吧。）

**Comment by willnewii** [comment]
是我的bug... 之前没有处理好.
嘿嘿,能用就行~   有啥问题随时提😁
