### ISSUE TITLE
bucket.domains 异常

### ISSUE THREAD

**Issue by relzhong** [willnewii/qiniuClient#11]
在操作他人共享的bucket 的时候不能获取bucket.domains.
![image](https://user-images.githubusercontent.com/12643564/33325774-306207b0-d48e-11e7-9fad-84b676569337.png)

**Comment by willnewii** [comment]
出现你截图中的问题,是程序启动时,token还没有加载,会有这个错,但不影响运行.跟你这个issue没关系.

针对这个issue,我测试的是,获取授权空间的domains,接口返回总是空数组.
已经给七牛提了个工单,有反馈我会告知你.  
多谢反馈.

**Comment by willnewii** [comment]
七牛技术已经做了回复.
授权的空间,是可以读取,但是api的确获取不到domain.这样就没办法访问,因为拼不出完整的资源链接.不过上传/删除 这些是可以用的.

**Comment by relzhong** [comment]
对于授权的空间，能否提供手动输入domain的方式， 这样方便复制链接地址.

**Comment by willnewii** [comment]
当然可以.  明天改改,提交了告诉你.

**Comment by willnewii** [comment]
@relzhong  你好,已经添加了输入框. 你可以试试~
