### ISSUE TITLE
AWS S3连接时报错：数据加载中,请稍后！

### ISSUE THREAD

**Issue by sunfengyun** [willnewii/qiniuClient#113]
buckets已经加载出来，在getAcl时出下如下图所示错误，页面一直处于“'数据加载中,请稍后'”，请问是什么原因？
![image](https://user-images.githubusercontent.com/13330392/71319886-237e2d00-24df-11ea-8268-dafc9c6dce55.png)

![image](https://user-images.githubusercontent.com/13330392/71319966-e23a4d00-24df-11ea-91bd-bd309da08d9d.png)

**Comment by sunfengyun** [comment]
![微信截图_20191222173513](https://user-images.githubusercontent.com/13330392/71320088-97b9d000-24e1-11ea-8876-b2f60859cc1e.png)
![微信截图_20191222173341](https://user-images.githubusercontent.com/13330392/71320090-98526680-24e1-11ea-968a-9b2e7fe4ac39.png)

**Comment by willnewii** [comment]
看报错应该说的是XML解析错误.  这个应该是某个依赖的内部错误.  
我这边并没有出现过相应错误. 可能需要您查看一下aws后台的设置?  具体也给不了您什么帮助.

您可以更新一下代码再试试?  我看您代码跟我的不太一样,不知道是您自己修改了,还是没更新.
[awsBucket.js#L31](https://github.com/willnewii/qiniuClient/blob/2189bfe5a789c905e74b03a99e47d1f1a4020c05/src/renderer/cos/awsBucket.js#L31)
