### ISSUE TITLE
希望添加剪贴板上传功能

### ISSUE THREAD

**Issue by cycychenyi** [willnewii/qiniuClient#115]
平时经常用TIM、微信剪贴图片，如果有剪贴板上传功能会方便很多，期待剪贴板上传功能！

**Comment by cycychenyi** [comment]
还希望加一下新建文件夹功能。感谢！

**Comment by cycychenyi** [comment]
还希望加一下右键菜单，直接在想要上传的文件夹下右键，上传剪贴板的图片。
这样对于网络图片也比较方便，不用另存到本地就可以上传。
（我好像有点贪心）

**Comment by cycychenyi** [comment]
还还还想像 Windows 文件管理器一样，可以设置单击打开还是双击打开。

**Comment by willnewii** [comment]
- 剪切板一直有问题,不一定能搞.
- 这个不会有.云存储的机制好像就没有文件夹的概念,都是文件.(软件里的文件夹是模拟出来的层级而已)
- 这个要看electron什么时候提供这样的能力,目前应该没有,也可能是我没找到.
- 单击打开还是双击打开,这个可以有.

抱歉啦,回的这么晚,还大多不能实现😂
