### ISSUE TITLE
打开界面黑屏怎么回事？

### ISSUE THREAD

**Issue by Rabbit2108** [willnewii/qiniuClient#116]
是缺少什么插件支持吗？我的是windows7系统

如图：
https://ae01.alicdn.com/kf/H924ead94548843dbbc27e662ada1e2b2O.jpg

**Comment by Rabbit2108** [comment]
64位系统

**Comment by willnewii** [comment]
这是直接下载的安装包?还是自己构建的？

**Comment by Rabbit2108** [comment]
> 这是直接下载的安装包?还是自己构建的？

好了，重装了下系统 - -！
