### ISSUE TITLE
npm 打包linux deb格式报错

### ISSUE THREAD

**Issue by thtomatic** [willnewii/qiniuClient#117]
错误日志：
``0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:linux:deb' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild:linux:deb',
4 verbose run-script   'build:linux:deb',
4 verbose run-script   'postbuild:linux:deb' ]
5 info lifecycle qiniuclient@0.4.2~prebuild:linux:deb: qiniuclient@0.4.2
6 info lifecycle qiniuclient@0.4.2~build:linux:deb: qiniuclient@0.4.2
7 verbose lifecycle qiniuclient@0.4.2~build:linux:deb: unsafe-perm in lifecycle true
8 verbose lifecycle qiniuclient@0.4.2~build:linux:deb: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/media/thtomatic/软件/qiniuClient/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle qiniuclient@0.4.2~build:linux:deb: CWD: /media/thtomatic/软件/qiniuClient
10 silly lifecycle qiniuclient@0.4.2~build:linux:deb: Args: [ '-c',
10 silly lifecycle   'cross-env ENV_DLL=true node .electron-vue/build.js && electron-builder --linux deb' ]
11 silly lifecycle qiniuclient@0.4.2~build:linux:deb: Returned: code: 1  signal: null
12 info lifecycle qiniuclient@0.4.2~build:linux:deb: Failed to exec build:linux:deb script
13 verbose stack Error: qiniuclient@0.4.2 build:linux:deb: `cross-env ENV_DLL=true node .electron-vue/build.js && electron-builder --linux deb`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid qiniuclient@0.4.2
15 verbose cwd /media/thtomatic/软件/qiniuClient
16 verbose Linux 4.15.0-30deepin-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build:linux:deb"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error qiniuclient@0.4.2 build:linux:deb: `cross-env ENV_DLL=true node .electron-vue/build.js && electron-builder --linux deb`
22 error Exit status 1
23 error Failed at the qiniuclient@0.4.2 build:linux:deb script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
``

**Comment by willnewii** [comment]
抱歉哈,我没有linux的环境,对这个也不熟.   你可以跟 #101 这几位沟通一下~

**Comment by abcfy2** [comment]
手头正好有一套deepin 15.11的笔记本，并未重现你的错误
