### ISSUE TITLE
筛选文件大小，文件显示空白

### ISSUE THREAD

**Issue by lampard-8** [willnewii/qiniuClient#118]
筛选文件大小，文件显示空白，都是文件夹里面的文件显示不出来

**Comment by willnewii** [comment]
筛选文件，还是按照目录显示的。 如果显示结果没问题的话，您可以进入的对应的目录查看.
比如:  /ab/cd/efg.jpg   /ww/cd/efg.jpg   您搜索efg ,会显示   ab 和 ww 两个目录,不会直接显示对应的文件。

还有一种情况是，您的云存储文件数量(跟大小无关哈)，大于5000，这个时候会自动开启分页，数据不全，结果就不准确了。

如果是以上两种情况，那应该没问题。  如果以上两种都不是，那就是我的问题了... 那就麻烦您说一下大概是什么云，文件量，方便的话截个图，我具体看看是什么问题了。

**Comment by lampard-8** [comment]
您好，我用的aws，按照时间或者文件大小筛选文件后的结果，如果是文件夹里面的文件就会不显示icon图标而且不能右键操作，普通上传的文件没问题。给您发了一张截图
![qiniu](https://user-images.githubusercontent.com/27675917/75409104-afcf2500-5952-11ea-954c-ba02d0e95589.png)

**Comment by willnewii** [comment]
了解了 正好在优化一块,我争取今天或者明天出个新版本.  请问您是什么系统？  win 还是mac？

**Comment by lampard-8** [comment]
win系统，感谢

**Comment by lampard-8** [comment]
还有一个问题就是上传一个文件夹，会不停的提醒文件上传成功，能不能上传文件夹的时候单独处理一下，只提醒一次文件夹上传完成。

**Comment by willnewii** [comment]
[云存储管理客户端-0.4.2-01-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.2-01-win.exe)
这是一个测试版的.您可以先试试~   显示问题,提醒问题应该都OK了~  有啥问题,再提哈~

**Comment by lampard-8** [comment]
您好，能给我一下这个版本的源码吗？我还想做一些别的修改，或者告诉我一下修改哪些文件可以修复这两个bug，感谢。

**Comment by willnewii** [comment]
因为还有其他的没完成,目前还没往master上合,最新代码就在dev分支下面.
上面那个链接,我自己测的时候没有那两个问题了,你如果只是使用的话可以直接用那个.
看代码的话，需要自己慢慢捋~  [mixin-resource](https://github.com/willnewii/qiniuClient/blob/dev/src/renderer/mixins/mixin-resource.js)  可以先看看这个文件
