### ISSUE TITLE
两个平台的同名桶会被覆盖

### ISSUE THREAD

**Issue by Rhythmicc** [willnewii/qiniuClient#120]
RT
如果我的阿里云和七牛云都有一个名称为`name`的桶，那么Client只显示后登录的`name`桶。

**Comment by willnewii** [comment]
每次只能登录一个平台. 我理解你的预期是在主页左侧的桶列表看到所有已授权的桶是吧?
比如:七牛有4个桶,阿里有3个桶,那么列表应该是七个桶?
如果是这样的话,目前还没有这个功能.当前只能显示一个平台的桶列表.
而你的问题是,刚巧两个平台里各有一个桶还是同名,然后以为是覆盖了？
如果是这个意思的话,我会尝试优化.如果不是的话,咱们再讨论~

各平台之间切换需要点击左边菜单的“切换”.

**Comment by Rhythmicc** [comment]
`刚巧两个平台里各有一个桶还是同名`
