### ISSUE TITLE
上传过程中，如果去下载其他文件或者其他操作会导致上传失败

### ISSUE THREAD

**Issue by lampard-8** [willnewii/qiniuClient#121]
您好，又来提bug了，哈哈，就是上传过程中，如果去下载其他文件或者其他操作会导致上传失败，是因为冲突吗，因为这个原因想加一个上传组件，可以实现断点续传之类的类似于百度网盘的功能。

**Comment by willnewii** [comment]
有可能.还真没试过这种场景. 不过最新版的,我已经把上传下载改成队列的方式了.估计...我是说估计,工作量不会太大. 周末我评估一下,然后给您答复.

**Comment by willnewii** [comment]
更新了,可以试试新版的.
- [云存储管理客户端-0.4.5.1-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.5.1-mac.dmg)
- [云存储管理客户端-0.4.5.1-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.5.1-win.exe)
我自己简单的测试了一下,上传和下载是不冲突了.  有需要的话,您可以试试~
