### ISSUE TITLE
请问你的Node 和 npm 版本是多少~

### ISSUE THREAD

**Issue by ChurchTao** [willnewii/qiniuClient#122]
请问你的Node 和 npm 版本是多少~

**Comment by willnewii** [comment]
node v10.14.2  npm 6.13.7
是有什么问题吗？

**Comment by abcfy2** [comment]
我用了nvm安装了最新的LTS版本，一样可以编译成功

**Comment by ChurchTao** [comment]
我也是最新的 LTS版本。我编译成 dmg 的时候报 内存溢出，然后编译成web的时候，似乎很多包找不到编译失败了

**Comment by willnewii** [comment]
这个不是web项目,没法编译的.
编译dmg报内存溢出的话,不知道您这边是不是自己手动修改过配置文件了.如果下载后,直接运行的是这一行[link](https://github.com/willnewii/qiniuClient/blob/135a6b4dce3b34c1008fe9c2428efaa36e79b5b0/package.json#L14).应该不会报错的.
