### ISSUE TITLE
京东云存储可以支持吗？

### ISSUE THREAD

**Issue by gylidian** [willnewii/qiniuClient#123]
如题

**Comment by willnewii** [comment]
应该可以.  周末有时间了,我试试~
有进展再回复你~

**Comment by willnewii** [comment]
已经更新了.可以试试~
- [云存储管理客户端-0.4.5-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.5-mac.dmg)
- [云存储管理客户端-0.4.5-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.5-win.exe)

**Comment by gylidian** [comment]
感谢您 @willnewii

**Comment by willnewii** [comment]
不用客气~

**Comment by zhuuvzhi** [comment]
京东云上传失败，版本:云存储管理客户端-0.5.1-mac

**Comment by willnewii** [comment]
抱歉,回复晚了.  之前的版本aws上传的确有问题.已经修复. 您可以再试试.

如果有需要,您可以再试试·  [云存储管理客户端-0.5.3-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.5.3-mac.dmg)
