### ISSUE TITLE
是否考虑增加重命名已保存的登录

### ISSUE THREAD

**Issue by abcfy2** [willnewii/qiniuClient#124]
作为运维人员，经常需要登录多组存储账号。所以希望能手改登录别名，方便查看对应的是哪个云存储的哪个账号，便于自己管理。

另外发现一旦账号注销，保存的登录凭证就会删除。建议改为注销之后，下次重开软件时跳转到已登录列表中，由用户自行选择是否删除已保存等登录凭据。

**Comment by willnewii** [comment]
![云存储管理客户端](https://user-images.githubusercontent.com/652003/77624575-fbd6af00-6f7c-11ea-8a54-f180b3fe852e.jpg)
在登录的时候,有个别名一栏,那里是可以修改的.

注销的话,个人觉得逻辑其实很简单.可能是我文案有歧义.注销就是清除当前正在使用的云存储的授权信息.

**Comment by abcfy2** [comment]
作者您好，我是说如果登录之后这个别名就被保存了，如果我还想重命名已保存的别名可以吗？目前感觉是没有这个功能的，我只能注销重新登录，并且起名新的别名保存，感觉麻烦了点

**Comment by willnewii** [comment]
哦哦~   了解了. 随后会加一个,点击左上角那个别名弹出修改框的小功能,应该能满足这方面的需求.

**Comment by willnewii** [comment]
代码已经提交了.  现在点击左上角的服务名称,可以直接修改别名.  有空同步代码试试,我就不打包了😂

**Comment by abcfy2** [comment]
感谢作者，已经在本地试用了，没问题了。
