### ISSUE TITLE
标题栏丢失应用图标

### ISSUE THREAD

**Issue by abcfy2** [willnewii/qiniuClient#126]
环境：Linux( Manjaro 19.0.2 KDE)

可执行程序方式: AppImage

![深度截图_选择区域_20200325170734](https://user-images.githubusercontent.com/5327677/77519914-4db70080-6ebb-11ea-94f0-f03f9a19e879.png)
![深度截图_选择区域_20200325170818](https://user-images.githubusercontent.com/5327677/77519918-4f80c400-6ebb-11ea-8859-9104ee1c07fd.png)

疑似设置窗口icon属性的时候出了问题？设置了错误的属性？

**Comment by willnewii** [comment]
这个就实在很抱歉了.我自己不会用Linux.是其他网友提的PR.我这边就提供不了什么实质性的帮助了.

如果您有能力自行构建的话,您可以尝试把./build/icon/512.png 这个文件重命名为  icon.png 再构建试试?

我看[文档](https://www.electron.build/icons)是这么写的.

**Comment by abcfy2** [comment]
OK，那个Linux build的PR是我提交的。我不是node开发，所以对electron和前段工程不是太熟悉，等我看下自己解决吧，到时候提交PR吧。

最近正好在用这玩意，正好可以学学electron

**Comment by willnewii** [comment]
哈哈  原来就是你哈~   那太简单了.  我看那个文档写的应该就是图标文件名没对上.你可以修改一下文件名试试看.
