### ISSUE TITLE
可以增加清除缓存的功能吗？

### ISSUE THREAD

**Issue by cycychenyi** [willnewii/qiniuClient#133]
有时候需要覆盖同名图片，清除缓存比较方便访问新的图片。

**Comment by willnewii** [comment]
菜单->设置->清除缓存   可以试试~

**Comment by cycychenyi** [comment]
> 菜单 -> 设置 -> 清除缓存 可以试试～

这个好像是清除软件的缓存？

抱歉抱歉，我没说清楚，想要清除 CDN 缓存的功能。

因为有的图片是自己做的，有时候会进行修改，需要覆盖原来的图片。

七牛云的 CDN 为了加速会进行缓存，这时候得到的总是旧的图片。

清除 CDN 缓存才能加载到新的图片。

**Comment by willnewii** [comment]
哦哦，理解了。 下午我先看看有没有相关的api哈。-------- 原始邮件 --------发件人： cycychenyi <notifications@github.com>日期： 2020年4月3日周五 10:52收件人： willnewii/qiniuClient <qiniuClient@noreply.github.com>抄送： 诗人的咸鱼 <willnewii@163.com>, State change <state_change@noreply.github.com>主    题： Re: [willnewii/qiniuClient] 可以增加清除缓存的功能吗？ (#133)

菜单 -> 设置 -> 清除缓存 可以试试～

这个好像是清除软件的缓存？
抱歉抱歉，我没说清楚，想要清除 CDN 缓存的功能。
因为有的图片是自己做的，有时候会进行修改，需要覆盖原来的图片。
七牛云的 CDN 为了加速会进行缓存，这时候得到的总是旧的图片。
清除 CDN 缓存才能加载到新的图片。

**Comment by willnewii** [comment]
更新了一下，有需要的话 可以试试新版。

需要注意的是：七牛有规定**每天文件刷新限额 500 个，目录刷新 10 个**,所以请注意别超了哈.这里调用跟七牛网页后台CDN->刷新预取  是一回事.

- [云存储管理客户端-0.4.5.2-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.5.2-mac.dmg)
- [云存储管理客户端-0.4.5.2-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.5.2-win.exe)

**Comment by cycychenyi** [comment]
哇好快啊，感谢作者！！

**Comment by willnewii** [comment]
有用就行~   有什么问题 继续提哈~  虽然不一定都满足😂
