### ISSUE TITLE
实用过程中发现的一些小问题

### ISSUE THREAD

**Issue by liwenbus** [willnewii/qiniuClient#136]
又拍云存储下
1、开启Https后返回的url依旧是http，在又拍云配置上也强制https了~搞得每次要手动加上个s。
2、勾选直接上传不显示对话框下，依然每次上传要点击对话框的确认~
3、上传完图片或文件后，原来目录下的文件全部会消失，刷新还没有用，只得返回上级后再进来才会显示文件。
小建议：
1、在设置增加点击关闭按钮后缩小到右下角任务栏的功能，而不是每次要在窗口选项下点击最小化，经常一不小心关闭就真的关闭了~

**Comment by liwenbus** [comment]
为啥那些文字会有删除线啊，哈哈哈

**Comment by willnewii** [comment]
收到~  这几天有别的活.有时间一个个确认一下~😀

**Comment by willnewii** [comment]
谢谢“测试”  😁.   
https的话需要注意,就算软件开始,还是需要又拍云后台配置支持的.

已经提交了新版本了,有需要的话可以试试.

**Comment by liwenbus** [comment]
> 谢谢“测试” 😁.
> https的话需要注意,就算软件开启,还是需要又拍云后台配置支持的.
> 
> 已经提交了新版本了,有需要的话可以试试.

好的，非常感谢你的无私付出！
