### ISSUE TITLE
上传没反应

### ISSUE THREAD

**Issue by PoplarYang** [willnewii/qiniuClient#138]
在minio界面用七牛s3登录，尝试这个按钮选中上传，没有任何反映，使用拖拽可以正常上传。

mac下，版本是0.4.6

![image](https://user-images.githubusercontent.com/15922385/82547384-3aa77080-9b8c-11ea-8bcf-129de35c3384.png)

**Comment by willnewii** [comment]
谢谢反馈~  问题已经修复了,如果有需要您可以更新一下.

咨询的一下,是什么场景下不直接用七牛而是用S3的兼容方式？

[云存储管理客户端-0.4.7-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.7-mac.dmg)

**Comment by PoplarYang** [comment]
修复的速度很快呀

我主要使用s3，通用性比较强，在使用各家国内外对象存储。

收费软件，免费软件用了一大堆，目前看来，您的产品还是比较全面的。

**Comment by willnewii** [comment]
哦哦~  原来是这样子.  您要不说，我都没反应过来可以这么用~
多些反馈~
