### ISSUE TITLE
大佬，可以在关闭客户端后后台不要继续运行吗，占用内存太大了

### ISSUE THREAD

**Issue by liwenbus** [willnewii/qiniuClient#140]
大佬，我发现在关闭软件后，后台依然会运行，而且任务管理器关都关不掉，占用内存还挺高，可不可以优化一下，关闭后不要运行~

**Comment by willnewii** [comment]
谢谢提醒.  
之前在win下面关闭是有问题.  [云存储管理客户端-0.4.7-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.7-win.exe) 
这个新版本,有需要的话 可以试一下,是否解决了你的问题.  我自己在win下面试了一下,没啥问题。  不过我用的比较少.

**Comment by liwenbus** [comment]
大佬，可以了哦！非常感谢！！！
