### ISSUE TITLE
mac 托盘设置保存报错

### ISSUE THREAD

**Issue by mayongze** [willnewii/qiniuClient#141]
版本: v0.4.7
京东云对象存储
设置-托盘设置 保存之后报错
![image](https://user-images.githubusercontent.com/22066360/83727330-76a40080-a677-11ea-9123-a302800d1ff2.png)

**Comment by willnewii** [comment]
重新梳理了一下托盘的使用逻辑，有需要的可以试一下新版~  多谢提交啦~
