### ISSUE TITLE
七牛主账号将一个空间授权给一个子账号访问，授权等级为"只读"，子账号访问无法访问

### ISSUE THREAD

**Issue by suzhan** [willnewii/qiniuClient#142]
七牛主账号将一个空间授权给一个子账号访问，授权等级为"只读"
子账号就不能使用qiniuClient , 登录时显示 "t is not iterable "

**Comment by willnewii** [comment]
您好，这个错误是软件抛出来的。
不过原因呢,是因为授权空间只有权限是“读写”，才能读取到。七牛API是这么规定的，我也没办法。
