### ISSUE TITLE
不能设置下载目录

### ISSUE THREAD

**Issue by longer008** [willnewii/qiniuClient#145]
不能设置下载目录

**Comment by willnewii** [comment]
之前版本是有这个问题.  更新了一个版本,有需要的话,您可以再试试~
- [云存储管理客户端-0.4.8-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.8-mac.dmg)
- [云存储管理客户端-0.4.8-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.8-win.exe)

**Comment by longer008** [comment]
好的，我昨天下载的时候只看见0.4.6版本的，现在看见0.4.8的了
