### ISSUE TITLE
登录不进去

### ISSUE THREAD

**Issue by MrJane** [willnewii/qiniuClient#147]
为啥我用七牛云密匙登录不进去 报 t is not iterable

**Comment by willnewii** [comment]
请问您是不是  授权账号？类似这种情况(#142)  或者账号下没有 创建空间呢？

**Comment by MrJane** [comment]
我是在七牛云密匙管理复制过来，新账号没有做啥操作



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 诗人的咸鱼 <notifications@github.com&gt;
发送时间: 2020年6月12日 11:20
收件人: willnewii/qiniuClient <qiniuClient@noreply.github.com&gt;
抄送: MrJane <523093962@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[willnewii/qiniuClient] 登录不进去 (#147)





 
请问您是不是  授权账号？类似这种情况(#142)  或者账号下没有 创建空间呢？

**Comment by willnewii** [comment]
哦哦~  那应该是因为您是新账号,里面没有一个存储桶,所以进不去.你可以先创建一个,再登录试试~

**Comment by willnewii** [comment]
#153
