### ISSUE TITLE
在使用阿里云oss存储时设置秘钥报错

### ISSUE THREAD

**Issue by cr-zhichen** [willnewii/qiniuClient#156]
# 在使用阿里云oss存储时设置秘钥报错

使用阿里云oss存储设置秘钥报错
v0.49  
win32  

![报错信息](https://www.chengrui.xyz/images/2020/07/01/Snipaste_2020-07-01_16-22-18.png)

![报错信息](https://www.chengrui.xyz/images/2020/07/01/Snipaste_2020-07-01_16-24-55.png)

**Comment by willnewii** [comment]
感谢反馈~  是我构建的时候出了问题。  已更新，有需要的话可以重新安装试试~
- [云存储管理客户端-0.4.9-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.9-1-mac.dmg)
- [云存储管理客户端-0.4.9-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.9-1-win.exe)
