### ISSUE TITLE
mac 下 npm run dev 无法运行

### ISSUE THREAD

**Issue by Airsola** [willnewii/qiniuClient#16]
npm run dev 后出现如下提示

         ERROR in ./app/src/renderer/App.vue
         Module build failed: Error:

         Vue packages version mismatch:

         - vue@2.3.0
         - vue-template-compiler@2.5.13

奇怪的的是在 package.json 里没有查到所使用的vue 版本？
vue本身是怎么引入的呢？

**Comment by willnewii** [comment]
请查看一下 app目录是否运行  npm i .  应该是自动会自动运行安装的.
有可能是项目目录下运行 npm i 安装过程中出现了错误,并没有完全安装.
