### ISSUE TITLE
上传图片后只有15b大小，无法上传

### ISSUE THREAD

**Issue by liwenbus** [willnewii/qiniuClient#162]
你好，0.5.0版本不知道为什么上传图片后变成一个15b大小的东西，请问怎么解决呢？

**Comment by liwenbus** [comment]
又拍云上传之后所有图片变成15B大小

**Comment by willnewii** [comment]
谢谢反馈.  的确有问题,问题也找到了. 不过不知道怎么改🤣   麻烦再等等哈~

**Comment by willnewii** [comment]
- [云存储管理客户端-0.5.1-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.5.1-mac.dmg)
- [云存储管理客户端-0.5.1-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.5.1-win.exe)

试一试~

**Comment by liwenbus** [comment]
好的好的，我试试

**Comment by liwenbus** [comment]
已经好了哦，哈哈哈，非常感谢你哦
