### ISSUE TITLE
希望增加网页版

### ISSUE THREAD

**Issue by SeireiA** [willnewii/qiniuClient#164]
如题，在外面每次下载客户端登录有点麻烦🌝麻烦了

**Comment by willnewii** [comment]
需求已添加至 #2

抱歉哈，这个需求短时间内满足不了。
1. 因为之前没考虑出web的。所以，从功能上改动就比较大。
2. web和node的差异，做出来肯定是个阉割版。至于阉多少，还不知道。要是阉的还不如官方的web，那就尴尬了
有时间我先评估一下.  您也可以说一下您比较关注的几个功能点.
