### ISSUE TITLE
请问又拍云开启了防盗链之后，图片无法显示，怎么设置白名单？

### ISSUE THREAD

**Issue by heson525** [willnewii/qiniuClient#167]
又拍云开启了防盗链，能看到文件，但是图片显示不出，请问白名单需要怎么设置呢？localhost不行。

**Comment by willnewii** [comment]
electron 默认Referer 是空.  你应该也勾选“禁止 Referer 为空” 了吧?  如果省事儿的话  去掉就行.  我这边的话,要想想怎么改才合适.

**Comment by heson525** [comment]
> electron 默认Referer 是空. 你应该也勾选“禁止 Referer 为空” 了吧? 如果省事儿的话 去掉就行. 我这边的话,要想想怎么改才合适.

我这边设置了`允许 Referer 为空` ，只是设置了白名单，这样还是现实不了图片，只能看到文件夹和图片数量。

**Comment by willnewii** [comment]
你试试在 设置里  “清除缓存” + “重新加载”  试试？  我这边如果设置“禁止 Referer 为空” 不显示. 去掉的话 是能正常显示的.

**Comment by heson525** [comment]
> 你试试在 设置里 “清除缓存” + “重新加载” 试试？ 我这边如果设置“禁止 Referer 为空” 不显示. 去掉的话 是能正常显示的.

感谢大佬，可以了，这样有用。
