### ISSUE TITLE
mac版无法下载，

### ISSUE THREAD

**Issue by Leader755** [willnewii/qiniuClient#168]
是不是您的服务器到期了

**Comment by willnewii** [comment]
我这边直接点链接是没反应.  可以试试把链接复制一下试试~  我这边能下载的.

**Comment by Leader755** [comment]
http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.5.1-mac.dmg

**Comment by Leader755** [comment]
1181012791@qq.com. 或者发到我邮箱吧。感谢

**Comment by willnewii** [comment]
就是这个链接.  你直接在浏览器里  输入一下  就好了呀？  不知道是哪里的问题,我这直接点是没反应的.在输入栏粘贴一下，回车就好了.

**Comment by Leader755** [comment]
没用的，下载不了。

**Comment by Leader755** [comment]
方便给发个邮箱吗，还是说是我vpn的缘故，按理说不走vpn啊。

**Comment by willnewii** [comment]
发送了,稍后查收一下.

**Comment by Leader755** [comment]
好的，感谢。
