### ISSUE TITLE
build:win32后，ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by PetersonLian** [willnewii/qiniuClient#174]
在win7机子上，build:win32后，打包出来的exe，执行之后，会发现3个文件err_file_not_found.
分别是static/dll/libs.css, lib.js, cos.js
不知道怎么搞。
需要去.electron-vue里头配置吗？怎么配？

**Comment by PetersonLian** [comment]
看了package.json之后。
需要在build:win32之前。
先分别跑build:dll build:dll-cos，把这些dll文件build出来。
之后就好了。

**Comment by willnewii** [comment]
抱歉，最近工作太多，忘回复你了。
是的，是需要先run  build:dll & build:dll-cos.  
[构建说明](https://github.com/willnewii/qiniuClient/wiki/%E6%9E%84%E5%BB%BA%E8%AF%B4%E6%98%8E),这里有个简单的说明.

不过我记得这文件缺失应该不影响运行吧？ 如果你机器性能不错,构建时没问题，速度也挺快的话，其实不需要这一步。

**Comment by PetersonLian** [comment]
我看webpack.main.config.js里头

    if (process.env.NODE_ENV !== 'production') {
        mainConfig.plugins.push(
                new webpack.DefinePlugin({
                    '__static': `${path.join(__dirname, '../static').replace(/\\/g, '\\\\')}`
                })
        );
    }
为何在production时候，主进程(main/index.js)里头的逻辑，不(webpakc.DefinePlugin)__static。我现在的情况是，我在Main逻辑里头，使用到了__static。
是设计的时候，就是这么设计，即“production时，main进程里头，不能使用__static”？还是，处于别的原因。
我现在是BrowserWindow new的时候，需要webPreference字段里头，使用preload.js，然后指定preload.js路径的时候，我使用了__static。
@willnewii

**Comment by willnewii** [comment]
这个是脚手架的[默认配置](https://simulatedgreg.gitbooks.io/electron-vue/content/cn/main-process.html).
我自己应该是没有用到. 
你可以按自己的需求修改试试？
