### ISSUE TITLE
0.5.1 文件夹改名卡更新中

### ISSUE THREAD

**Issue by liesauer** [willnewii/qiniuClient#177]
RT

![image](https://user-images.githubusercontent.com/8676741/101497309-bc14f380-3962-11eb-8ae7-3b5fd8660b84.png)

**Comment by liesauer** [comment]
windows版本

**Comment by liesauer** [comment]
貌似是遍历导致的？但是我就只有200多个文件，文件夹结构不超过4层，也不至于吧。

**Comment by liesauer** [comment]
另外删除任一文件后，整个文件夹就空了，点右上角刷新无效，只能返回上一层文件夹再进去才能刷新除出来。
![image](https://user-images.githubusercontent.com/8676741/101514919-b1b02500-3975-11eb-90c3-937caa99f9ee.png)

**Comment by willnewii** [comment]
这种情况是必现的吗？  我自己的文件夹改名&删除文件操作是正常的.不过我是mac.
如果必现的话,方便截个控制台吗？
晚一点，我找个win再确认一下.

**Comment by liesauer** [comment]
是的，必然出现，我是分页加载的，不确定和这个有没有关系。console和network都是空的。
![image](https://user-images.githubusercontent.com/8676741/101625484-60567300-3a13-11eb-8677-5e0204c36663.png)
