### ISSUE TITLE
下载链接挂了吗？

### ISSUE THREAD

**Issue by Volcano-Yang** [willnewii/qiniuClient#185]
![image](https://user-images.githubusercontent.com/43328103/107459939-2da33500-6b92-11eb-9176-196f7df06acc.png)

入口页面：doc的readme选择了mac版本链接下载
下载地址：http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.1-mac.dmg

**Comment by Volcano-Yang** [comment]
![image](https://user-images.githubusercontent.com/43328103/107460304-d6519480-6b92-11eb-97b7-b79adf169df4.png)
应该是只有这个地方旧版本的失效了

**Comment by willnewii** [comment]
下载链接已更新.  嗯,一般旧版本的我会删掉,所以提交记录里的下载链接会失效.
