### ISSUE TITLE
又拍云无法上传“大文件”

### ISSUE THREAD

**Issue by sxjeru** [willnewii/qiniuClient#200]
试了一个 6MB 大小的文件，虽然有明显的上传网络流量，但始终无法上传成功，定格在下图。
又拍云网页端可正常上传。

![image](https://user-images.githubusercontent.com/20513115/132326759-aa0a7edc-a20b-4f96-8fe4-e2dd45f7b2f1.png)

**Comment by willnewii** [comment]
不好意思 脱了这么久才回你.  才注意到你这个Windows？ 我明天再看看哈.  我平时用mac. 刚才试了一下是没问题.  不确定是不是个例哈.  有进度了再告诉你哈

**Comment by willnewii** [comment]
这个可以再试试？   我尝试上传了一个60M的文件,是成功的.  目前我没找到获取又拍云上传进度的回调,所以页面有点像卡死了.  如果有需要可以更新到最新的再试试

**Comment by sxjeru** [comment]
刚刚试了一下，没问题了。
感谢作者。
