### ISSUE TITLE
我要删除早于某日的所有文件，现在分页模式就是是噩梦

### ISSUE THREAD

**Issue by chmis8000** [willnewii/qiniuClient#22]
如标题
分页模式，按日期排序也是问题
思考解决方式：
1.能否调整分页大小，一页文件多点？
2.能否有 批量选择前100 、前50 的固定批量选，或指定数量批量选？

**Comment by willnewii** [comment]
大小当然可以调.分页只是一个简单的数据递增而已,不知道你说的噩梦是指?
日期排序又是什么问题呢?  日期排序也只是在已有文件里排序.
如果你文件量很大的话,假设一页500?  还会有你遇到的问题吗?  
麻烦具体说一下你的使用场景~

**Comment by willnewii** [comment]
添加了一个筛选功能. 你可以根据文件大小,文件上传日期进行筛选.
