### ISSUE TITLE
dev 环境  不显示日期跟大小

### ISSUE THREAD

**Issue by wwwsoftwares** [willnewii/qiniuClient#24]
可以看看  我用的是master分支

**Comment by willnewii** [comment]
请重新拉取代码,再试试.  如果还是不显示,可否提供错误提示.  控制台也可以看到七牛的请求返回结果,如果可以,麻烦也复制一份~

**Comment by willnewii** [comment]
更新iview后,renader函数调用错误导致的.已经更新
