### ISSUE TITLE
删除文件后刷新的文件列表文件数异常

### ISSUE THREAD

**Issue by yanweijia** [willnewii/qiniuClient#27]
在删除操作后页面拉取文件请求后页面文件数翻倍
| | |
|---|---|
|版本 v0.0.9,|直接从 release 中下载的, mac 和 win 都可以复现问题.|
|bucket | 私有空间|
## 具体问题复现方法:

打开对应的 bucket,先点击全选,然后点击删除.等待删除完成后页面显示的文件数翻倍(变成了60个). 但是实际上是重复的.实际存在的文件对应七牛云中只有30个文件.
![image](https://user-images.githubusercontent.com/8547395/40300416-c5b594f6-5d1b-11e8-9ad1-c3e249262cc1.png)

## 功能优化建议
- 设置中添加分页设置, 可以让用户自定义每页文件个数,
- 浏览文件列表的页面中加入翻页功能(页面跳转)
- 记录偏好:用户自定义的 bucket 域名,每次打开软件能够默认选上用户上次选择的 bucket 域名.

**Comment by willnewii** [comment]
问题已收到。最近手上有别的，要等一次才能改，抱歉.

**Comment by yanweijia** [comment]
不着急的,客户端确实很方便. 现在的客户端针对图床还有七牛的简单文件管理这个初期目标完全够用. 小而精够用了
