### ISSUE TITLE
能不能发一个win32 的dist版本出来 纯粹只是用不想编译

### ISSUE THREAD

**Issue by eric1lubow** [willnewii/qiniuClient#28]
有没有人传一个win32 的dist出来？
不是所有人会用gulp、npm 这套工具链？

**Comment by willnewii** [comment]
[qiniu.client-0.0.9-win.exe](https://github.com/willnewii/qiniuClient/releases/download/0.0.9/qiniu.client-0.0.9-win.exe)  试试这个能不能安装?
