### ISSUE TITLE
求助，发现若干问题

### ISSUE THREAD

**Issue by unssnu** [willnewii/qiniuClient#29]
作者大神你好，我在build出安装文件后，发现若干问题，还请麻烦看一下哈：

1.  删除文件列表上依然显示
2.  不显示文件大小，不显示上传日期
3.  七牛的AK和SK是否可以写到项目里？首次打开输入的形式感觉暴露出来不太好

我的运行环境是：win 10 64位，控制台没有显示报错

多谢~！

**Comment by willnewii** [comment]
你好,可否先使用release中的安装包,安装试一下.  [qiniu.client-0.0.9-win.exe](https://github.com/willnewii/qiniuClient/releases/download/0.0.9/qiniu.client-0.0.9-win.exe)

问题1:不太确定,我稍后会再确认一下,不好意思啦
问题2:有人提过,但是我这复现不了,而且我只有win7的机子.
问题3:你就把他当成登录页面就好了呀,你怎么都要填写一次对吧.而且写到项目里? 我怎么会知道你的AK，SK呢？🤓

**Comment by unssnu** [comment]
问题3： emmm，好像有点误会，我是想把这个包开放给许多人登录传图的，就相当于每个人都知道AKSK了。。。=。=
