### ISSUE TITLE
希望能够新增如下功能

### ISSUE THREAD

**Issue by CaeserZheng** [willnewii/qiniuClient#32]
首先这个工具做的真的很好，感谢作者的复出。

如果方便希望能够实现如下功能：
1、目录上传
2、支持文件覆盖上传
3、实现目录结构展示

**Comment by willnewii** [comment]
感谢反馈.   2稍后会加上.1,3 就要等等啦~
2.支持文件覆盖上传 应该会做.目前想到的方案是上传前检测一下是否有相同文件,提示覆盖.
3.实现目录结构展示 目前只有一级目录,我自己是觉得够用了🤣,后续看看以后是不是要加一个树状菜单.
1.之前也有别人提过,还没想好怎么做...
