### ISSUE TITLE
希望加入按日期、按目录批量删除的功能

### ISSUE THREAD

**Issue by anyfar** [willnewii/qiniuClient#33]
比如一键删除某时刻之前的所有文件，或者选择文件夹直接删除文件夹下所有文件。而不是先列出来再全选删除。

**Comment by willnewii** [comment]
软件里有一个筛选功能. 可以按文件大小,或者创建日期,筛选然后再删除.  应该会对你有帮助.
不过...这种批量操作,记得先自己试试.  我不确定没有bug🙏🙏🙏
按文件夹的还在开发中,还需要一点时间.抱歉啦,再等等

**Comment by anyfar** [comment]
筛选是对当前页面做筛选，还是不能批量删除

**Comment by willnewii** [comment]
你的数据量有多少?  七牛最多一次请求1000条.如果满足的话,你改个加载条数就行了.

**Comment by willnewii** [comment]
现在已经支持按目录批量删除
按日期的话,可以使用filter功能,先过滤,然后全选删除。功能是实现了,不过还是不好操作,以后会优化
不过还是最多操作1000条
