### ISSUE TITLE
建议兼容S3 API, 可支持多家对象存储

### ISSUE THREAD

**Issue by xiaolei0125** [willnewii/qiniuClient#38]
@willnewii  我已经测试过国内的七牛云，青云，腾讯COS, 阿里OSS，网易NOS基本上都是兼容S3 API的。
如果此项目使用S3 API，将可以支持多家对象存储

**Comment by willnewii** [comment]
收到~  之前没了解过S3.  我先去学习学习🤓

**Comment by willnewii** [comment]
@xiaolei0125  请教个问题.    
各家的对象存储的整体结构肯定都是类似的. 但是具体落地,各个接口还是有点差异.

我现在的做法是，应用的增删改查对接一个中间层,然后中间层再对接具体的服务商如:七牛或者腾讯。中间层作用就是尽量磨平平台差异，实现操作统一。这样我再支持一家的话，改动也不大，只需要新增一个实例，再实现对应增删改查，偶尔可能会处理一下平台不统一的地方，基本上就可以了。

我理解您的意思是，S3 API约等于一套云存储行业API的标准? 各家都有兼容S3 API 方案，可能就不会出现我上面说的平台差异问题，或者需要处理的平台差异性很小。但是，以七牛为例，在文档方面也没看到有哪里兼容S3的？

**Comment by xiaolei0125** [comment]
@willnewii  对，我的想法也是这样的，抽象出中间层来支持通用的操作，例如查询文件列表，上传，下载，删除等，然后对接不同的后端，对S3 API兼容性好的后端可以直接使用S3 API操作，不兼容的使用单独的API。
     对于云存储服务商对S3 API的兼容性，你可以使用AWS CLI S3或S3CMD等客户端工具进行测试。
     抱歉七牛云我记混了，没有使用过。但青云，腾讯COS, 阿里OSS，网易NOS等，我都使用工具测试过的，几乎都可以支持S3 API的增删改查操作，不过其中网易NOS对S3 API的兼容有点小问题，我已提了工单。 此外Ceph, Dreamhost, IBM COS, Minio等对象存储都是声称兼容S3  API的。
     用同一套标准协议，便于迁移和减少重复开发的成本；

**Comment by willnewii** [comment]
@xiaolei0125 
嘿嘿，那就好。我还以为有哪个文档我没看到，漏掉了什么“一劳永逸”的方法🙃。
随后好好看看S3的文档。
