### ISSUE TITLE
希望增加阿里云

### ISSUE THREAD

**Issue by wangbodbs** [willnewii/qiniuClient#44]
希望增加阿里云

**Comment by willnewii** [comment]
昨天有考虑,不过貌似阿里云OSS没有免费额度,我没测试账号,就没搞...   等我搞个账号,加上了,通知你.

**Comment by wangbodbs** [comment]
感谢感谢

**Comment by willnewii** [comment]
#48 阿里云基础功能已经接入完成了,不过还在dev.争取这周完成.

**Comment by willnewii** [comment]
支持阿里云的版本已经发布了,需要的话可以下载试试看~  目前只build了  mac版本  [mac v0.2.2](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.2.2-1207-mac.dmg)
