### ISSUE TITLE
希望增加阿里云和又拍云

### ISSUE THREAD

**Issue by fcwys** [willnewii/qiniuClient#45]
希望增加阿里云和又拍云对象储存，希望越来越好

**Comment by willnewii** [comment]
多谢 多谢.   我把支持平台的问题统一集中在一个问题了哈  #48

**Comment by willnewii** [comment]
Duplicate of #48

**Comment by willnewii** [comment]
支持阿里云的版本已经发布了,需要的话可以下载试试看~  目前只build了  mac版本  [mac v0.2.2](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.2.2-1207-mac.dmg)
