### ISSUE TITLE
文件数多会一直在加载中

### ISSUE THREAD

**Issue by huamaolin** [willnewii/qiniuClient#49]
能否修改为按页加载或者异步加载

**Comment by willnewii** [comment]
方案是可行的...
最早的版本本来做的就是分页加载.  不过会带来的问题,好多功能就不好使了.   文件夹模拟操作 / 导出URL / 修改文件夹名称.  我是觉得,做回分页,跟官网的控制后台就差不多了,然后就改成现在这种了.

异步的话,也试过,您是说加载一点显示一点对吧?  页面数据会乱跳. 因为我自己内部还有个排序.

我可以再试试加回分页试试.

**Comment by willnewii** [comment]
更新了一个版本. 默认在bucket文件数量大于5000,会使用分页加载. 有需要的话,可以试试.
