### ISSUE TITLE
私有空间的外链生成不正确

### ISSUE THREAD

**Issue by jemygraw** [willnewii/qiniuClient#5]
目前对于私有空间生成的外链不正确，无法访问，可以使用 https://github.com/qiniu/nodejs-sdk/blob/master/qiniu/storage/rs.js#L630 这里的方法来生成

**Comment by willnewii** [comment]
由于不能获取空间状态,目前的做法是在设置页面添加一个勾选项,手动选择空间的公开/私有状态.
