### ISSUE TITLE
关于自动复制URL的问题

### ISSUE THREAD

**Issue by AlliotTech** [willnewii/qiniuClient#50]
七牛云 URL 自动复制 出来的是http  而不是https。。。。 建议提供可选项~或替换为 HTTPS

**Comment by willnewii** [comment]
收到~  这个以后会加的.

**Comment by AlliotTech** [comment]
感谢~

**Comment by willnewii** [comment]
需求已添加至 #2

**Comment by solarhell** [comment]
如果能加一个自定义域名设置就更好了。

**Comment by AlliotTech** [comment]
域名是没有错误的。 你在七牛云后台设置了域名就好了。  只是我默认开启的 https 复制出的URL 不是HTTPS 才来提的需求

**Comment by solarhell** [comment]
是这样的，我用的腾讯云cos，有一个单独的CDN域名，我设置过CNAME了，所以有这样一个需求。

**Comment by willnewii** [comment]
> 如果能加一个自定义域名设置就更好了。

七牛云是在获取不到域名的情况下,我会有个输入框可以自定义域名.
其他的云的话,因为来回绑定域名闲麻烦我就偷懒没做.   OK 知道了  稍后会支持COS的域名.
如果你绑定过的话,他们应该有API可以直接获取.

**Comment by willnewii** [comment]
> 是这样的，我用的腾讯云cos，有一个单独的CDN域名，我设置过CNAME了，所以有这样一个需求。

需求已添加至 #2

**Comment by willnewii** [comment]
@AlliotTech  hi,你好 https的问题,已经发了个新版本,你可以在设置页选择支持 htpps .  再导出试试看.


@solarhell 腾讯云也支持自定义域名了， 在页面的左上角，有个输入框，设置你的自定义域名就可以了。

目前只构建了mac版本    [mac v0.2.2](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.2.2-1207-mac.dmg)

有什么问题  可以继续提呀~

**Comment by AlliotTech** [comment]
感谢~  希望能够构建一下win版本~

**Comment by AlliotTech** [comment]
感谢~
