### ISSUE TITLE
如果文件非常多，>10w，每次上传或删除都需要刷新3分钟以上

### ISSUE THREAD

**Issue by imyellow** [willnewii/qiniuClient#55]
非常棒，七牛唯一好用的客户端！
因为用做用户上传文件，所以零散琐碎的文件比较多，希望有个类似缓存机制，不用每次改动都线上拉所有文件列表下来，感谢。

**Comment by willnewii** [comment]
收到

**Comment by willnewii** [comment]
更新了一个版本.  默认在bucket文件数量大于5000,会使用分页加载.  有需要的话,可以试试.
