### ISSUE TITLE
cos上传无用

### ISSUE THREAD

**Issue by duchao1990** [willnewii/qiniuClient#61]
![image](https://user-images.githubusercontent.com/9289694/51098790-b3afee80-1807-11e9-8ec0-3beba9b90137.png)

**Comment by willnewii** [comment]
抱歉是我的bug...    有需要的话,可以重新下载 [云存储管理客户端-0.3.1-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.3.1-win.exe)

代码也已经更新,你也可以自行构建.

#62
