### ISSUE TITLE
Markdown常规操作，截图粘贴到工具，上传，粘贴链接地址

### ISSUE THREAD

**Issue by xiaobebe** [willnewii/qiniuClient#66]
Markdown常规操作，截图粘贴到工具，上传，粘贴链接地址

我日常用比较舒服的操作是截图，然后粘贴到工具，工具自动上传，并将返回的URL写到剪切板，然后直接粘贴到编辑器。

现在这样的流程貌似没有，不知道是不是我操作流程不对。

Mac系统，顶部工具栏展开不知道是干什么用的

<img width="324" alt="2019-03-04 6 50 26" src="https://user-images.githubusercontent.com/19386356/53728769-6d454a80-3eae-11e9-8735-9e18e41ca2d7.png">

 我这边是这样显示的

**Comment by xiaobebe** [comment]
我加入了从剪切板图片上传的功能，并建立了pull request

https://github.com/willnewii/qiniuClient/pull/67

**Comment by willnewii** [comment]
抱歉，这几天在外面。不能及时处理代码。要等周末了😊

**Comment by willnewii** [comment]
已经合并了.  不过有2个问题.  
粘贴板不支持多文件?  
粘贴板的文件会变大.  相当于上传的不是源文件.我看从DataTransferItemList 读取的size已经变了.

顶部工具栏就是一个上传记录,如果使用托盘上传的话,上传记录就会出现在那里.

**Comment by chaozding** [comment]
托盘图标没有找到呀

**Comment by willnewii** [comment]
楼主第一条留言 的图片,有个小牛图标,就是那个. @chaozding
