### ISSUE TITLE
七牛云老是『数据加载中，请稍后』

### ISSUE THREAD

**Issue by iamzxj** [willnewii/qiniuClient#69]
![2019-03-18_142513](https://user-images.githubusercontent.com/11895528/54510836-eaca8980-4989-11e9-8151-d1301d5def01.png)

**Comment by willnewii** [comment]
[错误码列表](https://developer.qiniu.com/kodo/api/3928/error-responses)
七牛云的文件里说,599 是服务端操作失败.  这个错误就不太清楚了.  
这个存储空间是你今天新建的吗?   你可以等明天再试一下吗？  猜测可能是有个接口,调用失败了.

**Comment by iamzxj** [comment]
嗯嗯 是今天新建的，这个项目可以编译成web端么？

**Comment by iamzxj** [comment]
第二天操作就好了  这问题也是蛮奇怪

**Comment by willnewii** [comment]
不可以编译成web端.或者说,没法直接用.

[七牛云-数据统计接口](https://developer.qiniu.com/kodo/api/3906/statistic-interface)
为了统计当前空间大小和文件数,我调用了七牛云的统计接口.文档里有说,统计接口返回的是前一天的数据.所以所以如果是新空间的话,该接口就报错了(感觉这样做不太合适).
我也已经处理了.   多谢反馈~
#71
