### ISSUE TITLE
ERROR in main.js from UglifyJs

### ISSUE THREAD

**Issue by parkyang** [willnewii/qiniuClient#7]
git clone后，执行 npm i&npm run build:darwin
报错：
ERROR in main.js from UglifyJs
Unexpected character '`' [main.js:1058,8]

ERROR in main.js from UglifyJs
Unexpected character '`' [main.js:1058,8]

node v9.1.0
npm 5.5.1

**Comment by willnewii** [comment]
已经修改了.  更新试试看~
