### ISSUE TITLE
请问一下七牛云总是显示数据加载中是什么原因

### ISSUE THREAD

**Issue by Calshon** [willnewii/qiniuClient#72]
请问一下七牛云总是显示数据加载中是什么原因
不是新建的空间 已经建立了一段时间了

**Comment by willnewii** [comment]
可否看一下控制台输出?   菜单  视图-》开发者工具

**Comment by Calshon** [comment]
![image](https://user-images.githubusercontent.com/32190994/55390009-e9dc4f00-5568-11e9-92d6-9a642902eac5.png)

**Comment by Calshon** [comment]
大概知道问题的原因了 是因为我们这的文件太多了 已经改了加载方式了 现在正常了

**Comment by Calshon** [comment]
谢谢拉 功能很强大👍

**Comment by perfect-network** [comment]
还是不行  同样问题

**Comment by perfect-network** [comment]
internal/process/warning.js:18 (node:32480) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by perfect-network** [comment]
望尽快修复。。。第一次使用就这样体验很不好。。。。。

**Comment by perfect-network** [comment]
有没有大佬啊  我想自己改改，但是在win10 和 centos7.6 都
```
npm i
```
都无法成功

**Comment by willnewii** [comment]
@perfect-network   可否给个具体的错误代码？  
如果文件量过大导致加载时间过程,请使用新版.  
如果是其他愿意报错,控制台一般会有输出. 另:
> DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

这个不会导致不能使用...

npm i 无法成功...这个跟我没啥关系吧
