### ISSUE TITLE
[用户体验] 我觉得可以把单击预览的功能改成单击选中

### ISSUE THREAD

**Issue by DoneSpeak** [willnewii/qiniuClient#73]
我觉得可以把单击预览的功能改成单击选中，现在的单击预览导致我总是误操作。按照所有文件系统的使用习惯，都是以双击作为打开，单击作为选中，我觉得这样会好很多。
增加一个双击预览的功能，替换原本的单击预览。

**Comment by willnewii** [comment]
#74 已修改.多谢提醒.
