### ISSUE TITLE
七牛文件夹不能下载，也不能统计文件夹有多少文件

### ISSUE THREAD

**Issue by ulifuqiang** [willnewii/qiniuClient#75]
七牛文件夹不能下载，也不能统计文件夹有多少文件

**Comment by willnewii** [comment]
😅可否把问题描述的清楚一些...

**Comment by ulifuqiang** [comment]
![QQ截图20190415010721](https://user-images.githubusercontent.com/25083314/56096444-e78bd480-5f1a-11e9-9b4c-9d6f9e23bd3a.png)

批量下载没法下载文件夹里面的内容，这些文件夹也不能右键查看详情，比如文件夹里面有多少文件。

**Comment by ulifuqiang** [comment]
同一个七牛账号，有一个空间可以选择文件夹，有一个空间不能选择,

**Comment by willnewii** [comment]
你是开发? 这里有个大概的解释.[数据加载方式](https://github.com/willnewii/qiniuClient/wiki/%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E6%96%B9%E5%BC%8F)
等我想想有没有更好的方式,解决这个问题.

> 同一个七牛账号，有一个空间可以选择文件夹，有一个空间不能选择,
这句话没看懂?

**Comment by ulifuqiang** [comment]
![QQ截图20190415135609](https://user-images.githubusercontent.com/25083314/56110254-45093b00-5f86-11e9-8118-31e809cc813c.png)
我有l两个存储空间，一个空间是正常的一个空间不正常，就是右键文件夹的时候，kashen这个空间就是显示的0文件0B，wangdaijining这个空间就能显示正常的文件夹个数和大小。而且也能直接选择一个文件夹就可以下载。kashen那个空间就不能下载。

**Comment by willnewii** [comment]
哦哦 懂了.  原因就是我上面给你贴的那个.👉[数据加载方式](https://github.com/willnewii/qiniuClient/wiki/%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E6%96%B9%E5%BC%8F)

kashen 这个空间文件个数大于5000,会默认开始分页加载,所以按文件夹下载,文件夹属性的功能就废了.
wangdaijining  这个文件个数应该没有超过5000吧? 所以就默认全部加载,这样功能就全部正常了.

大文件这块,目前我也没什么更好的解决方案,真是抱歉~

**Comment by ulifuqiang** [comment]
kashen 9万多文件8G
wangdaijining 7.1万 4.9G

都是超过了5000的哦

**Comment by ulifuqiang** [comment]
你的意思是单文件夹 文件数超过5000还是空间总计呢。

**Comment by willnewii** [comment]
空间总计

七牛有一个接口,可以获取到前一天的空间统计信息.我会根据这个接口返回的文件数来判断是全部加载还是分页加载.
但是这个接口有延迟,他并不是实时的. 如果wangdaijining这个空间不是今天文件数才涨到7w多的话,那就尴尬了😓 🐛...   明天我再好好测一下哈.

**Comment by ulifuqiang** [comment]
都开全部加载呗，哦那客户端的人大概都是想下载文件回来的。慢点就慢点咯，或者给个开关

**Comment by willnewii** [comment]
嗯，好的。随后会加上。多谢 多谢~  😀

**Comment by ulifuqiang** [comment]
大概什么时候能用上呢

**Comment by willnewii** [comment]
争取这2，3天吧.  mac的话明天改改应该就能用上.win的话,需要等我找个win的电脑😂

**Comment by ulifuqiang** [comment]
win的电脑有了么？能用我的电脑打包吗

**Comment by willnewii** [comment]
不好意思 拖了这么久.  已经更新了.   [0.3.2-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.3.2-win.exe)
