### ISSUE TITLE
七牛能不能加个原图保护的存储空间加图片处理样式功能

### ISSUE THREAD

**Issue by hlwen** [willnewii/qiniuClient#76]
在空间开启了原图保护，就不能设置样式来加载原图保护空间的图片，可以考虑添加一下这功能

**Comment by willnewii** [comment]
如果你是mac用户的话,可以下载这个.[0.3.2-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.3.2-mac.dmg)
如果是win的话,再等等哈,可能还要过一两天.

更新后,还需要自己修改一下.[七牛云开启原图保护后图片不显示](https://github.com/willnewii/qiniuClient/wiki/%E4%B8%83%E7%89%9B%E4%BA%91%E5%BC%80%E5%90%AF%E5%8E%9F%E5%9B%BE%E4%BF%9D%E6%8A%A4%E5%90%8E%E5%9B%BE%E7%89%87%E4%B8%8D%E6%98%BE%E7%A4%BA)

**Comment by willnewii** [comment]
你好,新版已经更新.   v0.3.2  可以下载试试看~
