### ISSUE TITLE
本地打包处理的没有图标

### ISSUE THREAD

**Issue by imyellow** [willnewii/qiniuClient#77]
不好意思，release 一直没有更新所以下载自己打包了，但有个问题，打包了之后图标不见了，请问是哪里设置的问题吗？
![image](https://user-images.githubusercontent.com/3270774/56629818-630b2580-6681-11e9-8a8d-35df0c8a0e63.png)

**Comment by willnewii** [comment]
mac 的吗?  昨天刚build了一个版本  [0.3.2-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.3.2-mac.dmg)

字体图标没有打进去,我也是昨天才发现这个问题的.
```shell
//你可以先执行这个,然后再执行构建命令,应该就没问题了.
npm run build:dll
```
