### ISSUE TITLE
能否支持ucloud的对象存储？

### ISSUE THREAD

**Issue by stgreyboy** [willnewii/qiniuClient#79]
希望作者新增，感谢提供！

相关文档 https://docs.ucloud.cn/storage_cdn/ufile/index

**Comment by willnewii** [comment]
[ufile-nodejssdk](https://github.com/ufilesdk-dev/ufile-nodejssdk),看了一下他们家的sdk. 
这应该是我见过最那啥的SDK了.可能和他们业务有关系吧.  这个目前应该不会支持，真是抱歉😞
