### ISSUE TITLE
为啥安装不了？

### ISSUE THREAD

**Issue by Veitor** [willnewii/qiniuClient#8]
经常从github上搞下来的前端项目npm install阶段就挂了。。明明按照步骤来的。。却总是一些莫名其妙的问题。。前端怎么这么神奇。。。
![_20171121141531](https://user-images.githubusercontent.com/7483890/33057549-811f2caa-cec6-11e7-8a7b-5a2e06672ff0.png)
这是啥问题。。什么超时了。。

![qq 20171121141540](https://user-images.githubusercontent.com/7483890/33057550-816bfbf2-cec6-11e7-8b9d-df02d93c9ac0.jpg)

最后还是失败了啊

**Comment by willnewii** [comment]
换  cnpm  试试？

**Comment by relzhong** [comment]
npm 的版本太久了，升级一下吧
