### ISSUE TITLE
 通过剪切板粘贴上的图片，会无法刷新图片列表和自动复制链接

### ISSUE THREAD

**Issue by EsunR** [willnewii/qiniuClient#80]
运行环境是win10 64位，控制台会出现以下报错，能否修复一下呢，谢谢

![image](https://user-images.githubusercontent.com/30311024/57220851-7c23b700-702f-11e9-82b0-ef9ceba9619a.png)

**Comment by willnewii** [comment]
收到.bug会修复.但是不推荐使用这个功能.所以虽然合并的小伙伴的提交,但是这个功能没写进更新记录里.

#66
