### ISSUE TITLE
批量上传是一直卡在文件上传中

### ISSUE THREAD

**Issue by FlickerMi** [willnewii/qiniuClient#81]
拖入文件夹上传一直卡在文件上传中，有时能上传成功一个，然后一直就卡住了。
![image](https://user-images.githubusercontent.com/9433534/57563884-27d55a00-73d6-11e9-84a0-2d770f778da5.png)

console内容如下：

![image](https://user-images.githubusercontent.com/9433534/57563882-20ae4c00-73d6-11e9-8851-ed8b0d6a1fd5.png)

软件很好用，感谢开发者的付出。

**Comment by willnewii** [comment]
七牛云?

**Comment by FlickerMi** [comment]
> 七牛云？

对的，忘记讲了。

**Comment by FlickerMi** [comment]
> 七牛云？

@willnewii 对的，忘记讲了。

**Comment by Whosc** [comment]
我也遇到同样的问题了

**Comment by willnewii** [comment]
@Whosc 你是win？ 还是mac？

**Comment by Whosc** [comment]
win

**Comment by FlickerMi** [comment]
补充：我是mac

**Comment by willnewii** [comment]
@FlickerMi  @Whosc  抱歉,我这边没法复现这个问题. 不知道你们方不方便借我用一下你们的七牛token...(有点冒昧😂)

**Comment by Chen-WeiZhen** [comment]
> @FlickerMi @Whosc 抱歉,我这边没法复现这个问题. 不知道你们方不方便借我用一下你们的七牛token...(有点冒昧😂)
可以复现，比如你上传之后可能出去了，先让计算机睡眠一下，然后重新点亮计算机。发现卡死在上传中.....

**Comment by willnewii** [comment]
更新了一下七牛SDK.  如果还有需要可以试试新版的,看看是否还有卡的情况.
