### ISSUE TITLE
现在版本下载功能是有问题的吗？

### ISSUE THREAD

**Issue by powerZhous** [willnewii/qiniuClient#82]
![image](https://user-images.githubusercontent.com/27330767/57600504-978d4580-758c-11e9-98f4-7b25f00cf208.png)

**Comment by willnewii** [comment]
请问您这个空间是个私有空间吗？

**Comment by powerZhous** [comment]
对的

**Comment by powerZhous** [comment]
还是说不能关联私有空间？要用公开的？

**Comment by willnewii** [comment]
您可以在"设置"页面 手动勾选相应私有空间.  
这个因为七牛没有提供过去空间状态的api，只能靠用户手动选择.在不知道是私有空间的情况下，资源链接默认是公开的,就会出现访问错误,而导致下载错误.
