### ISSUE TITLE
批量导出资源URL没反应

### ISSUE THREAD

**Issue by zhengkangzhong** [willnewii/qiniuClient#85]
点了又上角批量导出资源URL这个功能，没有反应，是该功能还没实现吗

**Comment by willnewii** [comment]
抱歉,是个bug.已经修复了.
如果你使用的mac的话,可以重新下载试试. [mac-0.3.2](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.3.2.1-mac.dmg)
