### ISSUE TITLE
URL上传,现在URL也支持批量上传了

### ISSUE THREAD

**Issue by FY666l** [willnewii/qiniuClient#87]
介绍里面说的这个URL上传在哪呢。不知道如何使用

**Comment by willnewii** [comment]
![](http://blog-res.mayday5.me/img/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF_%E5%92%8C_URL%E4%B8%8A%E4%BC%A0_%E7%8E%B0%E5%9C%A8URL%E4%B9%9F%E6%94%AF%E6%8C%81%E6%89%B9%E9%87%8F%E4%B8%8A%E4%BC%A0%E4%BA%86_%C2%B7_Issue__87_%C2%B7_willnewii_qiniuClient.jpg)

这个按钮.
放入你要上传的图片链接就好了.
