### ISSUE TITLE
请求支持Amazon S3

### ISSUE THREAD

**Issue by wuhang2003** [willnewii/qiniuClient#89]
支持完国内的对象存储该考虑国外的了，比如亚马逊S3

**Comment by willnewii** [comment]
新版本已经支持亚马逊S3了.不过,只是简单的支持了一下之前的功能.
如果您时mac用户,可以直接下载更新.
如果是win用户的话,需要再等等,最近手上没有win的机器,没法构建.

**Comment by willnewii** [comment]
[云存储管理客户端-0.4.1-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.1-win.exe)
