### ISSUE TITLE
webp preview support

### ISSUE THREAD

**Issue by RikkaBlue** [willnewii/qiniuClient#90]
`webp`  有很多优势，压缩率高、支持透明像素等等，我自己也常用这个格式，不知是否能够添加 `webp` 格式的预览支持。  
谢谢

**Comment by willnewii** [comment]
收到~  随后会加上~

**Comment by RikkaBlue** [comment]
> 收到~ 随后会加上~

感谢，幸苦了

**Comment by willnewii** [comment]
不好意思拖的有点久。  代码已经更新了. 如果你是mac用户的话,可以直接下载0.3.3版本了.[云存储管理客户端-0.3.3-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.3.3-mac.dmg)
如果是win的话,还需要再等等,我家里好像网络有问题,win老是构建失败,或者也可以自行构建

**Comment by RikkaBlue** [comment]
> 不好意思拖的有点久。 代码已经更新了. 如果你是mac用户的话,可以直接下载0.3.3版本了.[云存储管理客户端-0.3.3-mac.dmg](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.3.3-mac.dmg)
> 如果是win的话,还需要再等等,我家里好像网络有问题,win老是构建失败,或者也可以自行构建

谢谢，尝试自己 build 了一下，但是
![image](https://user-images.githubusercontent.com/46104879/64070937-8a61a700-cca0-11e9-8c05-6d8c75ccb46a.png)
应该是哪里出错了，所以还是得麻烦你了。
