### ISSUE TITLE
替换了文件不显示最新的

### ISSUE THREAD

**Issue by ying83811** [willnewii/qiniuClient#94]
图片被替换掉后，客户端一直显示老的图片内容，刷新/重开程序都不行。已经在七牛云上清理该图片的cdn缓存，网页上显示的是最新内容，但就是客户端显示的是老的。即使是删除了重新上传，客户端还是显示老的内容。不知道是我操作不对还是怎么的，另外建议加个清缓存的功能呢。
望回复，感谢！！
我系统是win764位，家里的电脑和公司的电脑一样，装了客户端都有这个问题。

**Comment by willnewii** [comment]
再设置菜单里添加了一个清空缓存,如果有需要的话,您可以试试~
[云存储管理客户端-0.4.1-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.1-win.exe)

**Comment by ying83811** [comment]
清除缓存这个功能完美解决了我遇见的问题，非常感谢！

**Comment by ying83811** [comment]
> 再设置菜单里添加了一个清空缓存,如果有需要的话,您可以试试~
> [云存储管理客户端-0.4.1-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.1-win.exe)

清除缓存这个功能完美解决了我遇见的问题，非常感谢！
