### ISSUE TITLE
能否支持阿里云oss的内网连接地址 

### ISSUE THREAD

**Issue by JiangChenYang** [willnewii/qiniuClient#96]
将工具软件放在阿里云内网服务器内使用的时候  走内网传输得到的速度将会得到明显的提升

**Comment by willnewii** [comment]
添加了在登录页是否走内网的选择.不过因为我没有阿里云的服务器,也没测试.需要您自行测试一下.
[云存储管理客户端-0.4.1-beta-win.exe](http://blog-res.mayday5.me/file/%E4%BA%91%E5%AD%98%E5%82%A8%E7%AE%A1%E7%90%86%E5%AE%A2%E6%88%B7%E7%AB%AF-0.4.1-beta-win.exe)

**Comment by JiangChenYang** [comment]
这个安装包不行内网打钩了以后登陆不上  源代码应该是在sdk的配置里  internal:true  加一条这个

**Comment by willnewii** [comment]
的确用的是这个参数...您是在云主机上测试的哈？
晚上我在看看这些参数具体的使用场景.抱歉啦.
https://github.com/willnewii/qiniuClient/blob/ad48de816b2147c912fa44491266e259711195aa/src/renderer/cos/ali.js#L13

**Comment by JiangChenYang** [comment]
好的没事哒  源码上有这部分内容的话我也可以更新拉下来调试看看  十分好用这个工具。

**Comment by willnewii** [comment]
> 好的没事哒 源码上有这部分内容的话我也可以更新拉下来调试看看 十分好用这个工具。

好嘞. 那您的自己确认一下最好了. 您可以直接把按行代码写死成true. 我理解的是,只要勾选内网,然后就可以在阿里云的主机上运行了吧?
