### ISSUE TITLE
文件夹2000多个小的子文件，总的文件夹传成功后，但是一直桌面提示上传成功

### ISSUE THREAD

**Issue by xingwen93** [willnewii/qiniuClient#97]
![image](https://user-images.githubusercontent.com/16276222/65318496-45120480-dbd0-11e9-8f29-69f7e3283eb7.png)
文件夹2000多个小的子文件，总的文件夹传成功后，但是一直桌面提示上传成功

**Comment by willnewii** [comment]
Duplicate of #98
